apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-access-controller-webhook-configmap
  namespace: admission-webhook-ns
data:
  webhookserverconfig.yaml: |
    containers:
    - name: sidecar-nginx
      image: nginx:1.12.2
      imagePullPolicy: Always
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx
    volumes:
    - name: nginx-conf
      configMap:
        name: nginx-configmap
